#!/bin/sh

dir=$(pwd)
cd ~/.local/bin/redterminal

if expr $1 = "regenerate" > /dev/null ; then
	python regenerate.py $2
elif expr $1 = "display" > /dev/null ; then
	python display.py $2
else
	notify-send "Please use provide a valid argument"
fi

cd $dir
